#!/bin/bash

set -e

./disable-unity-shopping-scopes
./enable-apt-canonical-partners-sources
./enable-apt-automatic-security-updates
./update-ubuntu
./disable-nouveau
./disable-fn-key-for-function-keys
./enable-swedish-keyboard
./enable-natural-scrolling
./compensate-for-retina
./install-tilda-and-byobu
./install-vim
./save-bash-history
