#!/bin/bash

set -e
cd $(dirname ${0})

./all-2-developer-base

./install-nvm-and-nodejs
./add-node_modules-bin-to-path
./install-ruby
./install-network-utils
./install-chrome
./install-firefox-trunk
./install-dillo
./install-webstorm
