#!/bin/bash

set -e
cd $(dirname ${0})

./all-2-developer-base

./install-nvm-and-nodejs
./install-ruby
./install-network-utils
./install-chrome-dev
./install-firefox-trunk
./install-dillo
./install-webstorm
