#!/bin/bash

set -e
cd $(dirname ${0})

./disable-unity-shopping-scopes
./enable-apt-canonical-partners-sources
./enable-apt-automatic-security-updates
./update-ubuntu
./disable-fn-key-for-function-keys
./disable-some-keyboard-shortcuts
./enable-swedish-keyboard
./enable-natural-scrolling
./enable-week-numbers
./compensate-for-retina
./install-tilda-and-byobu
./install-vim
./save-bash-history
