#!/bin/bash

set -e

## Ubuntu with Unity / Gnome Shell:
#gsettings set org.gnome.settings-daemon.peripherals.touchpad natural-scroll true

# Works everywhere, including Xubuntu:
POINTER="pointer = 1 2 3 5 4 7 6 8 9 10 11 12"
grep "$POINTER" ~/.Xmodmap || echo $POINTER >> ~/.Xmodmap
xmodmap ~/.Xmodmap
