#!/usr/bin/env bash

# Finds the scripts here which are not listed in any of the `all-*` scripts.

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"

find . \
  -maxdepth 1 \
  -type f \
  -perm /u+x \
  -not -name all-\* \
  -exec sh -c 'grep "${1}" all-* >/dev/null || echo "${1}"' _ {} \;
