#!/bin/bash

# Finds the scripts here which are not listed in any of the `all-*` scripts.

set -e 

for section in sys user; do (cd $section && for i in $(find . -maxdepth 1 -type f -not -name all-\*); do (grep $i all-* > /dev/null || (echo $section/$i | sed -r 's/\/\.\//\//')); done;); done;
