#!/bin/bash

set -e

which aptitude || sudo apt-get install -y aptitude
sudo aptitude install -y lightdm gnome-screensaver

mkdir -p ~/.config/autostart
cat > ~/.config/autostart/gnome-screensaver.desktop <<EOF
[Desktop Entry]
Type=Application
Exec=gnome-screensaver
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=gnome-screensaver
Name=gnome-screensaver
Comment[en_US]=
Comment=
EOF