#!/bin/bash

set -e

which skypeforlinux && exit 0

which aptitude || sudo apt-get install -y aptitude
which gdebi || sudo aptitude -y install gdebi-core

cd $(mktemp -d)
wget https://go.skype.com/skypeforlinux-64.deb -O skypeforlinux-64.deb
sudo gdebi --non-interactive skypeforlinux-64.deb
