#!/bin/bash

set -e

sudo apt-add-repository -y ppa:webupd8team/java
which aptitude || sudo apt-get install -y aptitude
sudo aptitude update
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
sudo aptitude install -y oracle-java8-installer
