#!/bin/bash

set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd "${DIR}"

## Install docker
./update-ubuntu
./install-docker

## Filter incoming traffic to docker (ufw is not good enough with docker swarm)
#sudo su - $USER -c "docker run -d --name captain-firewall --env FW_SERVICE=captain --env FW_PROTO=tcp --env FW_PORTS=22,80,443 --restart=always --cap-add=NET_ADMIN --net=host hugojosefson/docker-firewall"

## Remove any existing captain password
if [ -e /captain/config.conf ]; then
    echo
    echo "Removing existing captain password..."
    sudo su - $USER -c "docker service scale captain-captain=0"
    sudo sed /hashedPassword/d -i /captain/config.conf
    sudo su - $USER -c "docker service scale captain-captain=1"
fi

## Install captainduckduck
sudo mkdir -p /captain
sudo docker run -v /var/run/docker.sock:/var/run/docker.sock hugojosefson/captainduckduck:apex

## Change default password
OLD_PASS="captain42"
NEW_PASS=$(< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-32};echo;)
COOKIE_JAR=$(mktemp)

which jq || sudo apt install -y jq
echo
echo "Logging in to change default captain password..."
unset TOKEN
until [ ${#TOKEN} -ge 20 ]; do
    LOGIN_RESPONSE=$(curl -sS \
        --junk-session-cookies \
        --cookie "${COOKIE_JAR}" \
        --cookie-jar "${COOKIE_JAR}" \
        localhost:3000/api/v1/login \
        -X POST \
        -H "Content-Type: application/json;charset=UTF-8" \
        -H "x-namespace: captain" \
        --data "{\"password\":\"${OLD_PASS}\"}" || true)
    STATUS=$(echo "${LOGIN_RESPONSE}" | jq -r .status)
    TOKEN=$(echo "${LOGIN_RESPONSE}" | jq -r .token)
    if [ "x$STATUS" != "x100" ]; then
        echo "${LOGIN_RESPONSE}"
    fi
    sleep 2
done

echo
echo "Changing captain password..."
curl -sS \
    --cookie "${COOKIE_JAR}" \
    --cookie-jar "${COOKIE_JAR}" \
    localhost:3000/api/v1/user/changepassword \
    -X POST \
    -H "Content-Type: application/json;charset=UTF-8" \
    -H "x-captain-auth: ${TOKEN}" \
    -H "x-namespace: captain" \
    --data "{\"oldPassword\":\"${OLD_PASS}\", \"newPassword\":\"${NEW_PASS}\"}"

rm ${COOKIE_JAR} || true

## Instructions
IP="$(curl -sS https://api.ipify.org/)"
echo
echo
echo "=============================================================================="
echo "Go to http://${IP}:3000/ and configure your domain."
echo "Default captain password has been changed to ${NEW_PASS}"
echo
echo "See also https://github.com/githubsaturn/captainduckduck/wiki/Getting-Started"
echo "=============================================================================="

popd