#!/bin/bash

set -e

ORIGINAL_DIR="$(pwd)"

if [ ! -d /opt/android-ndk/ ]; then
  which aptitude || sudo apt-get install -y aptitude
  which curl || sudo apt-get install -y curl
  which wget || sudo apt-get install -y wget
  
  DOWNLOAD_URL=$(curl --silent https://developer.android.com/tools/sdk/ndk/index.html | hxpipe | grep ^Ahref | grep ndk | grep linux | cut -d ' ' -f 3)
  FILENAME=$(echo $DOWNLOAD_URL | rev | cut -d '/' -f 1 | rev)
  FILE=$(dirname $(mktemp))/$FILENAME
  
  wget --continue ${DOWNLOAD_URL} -O $FILE
  DIR=$(tar tf $FILE |head -n 1|cut -d '/' -f 1)
  
  sudo chown $USER:$GROUP /opt
  tar xf $FILE -C /opt
  cd /opt
  rm android-ndk || true
  ln -s $DIR android-ndk
  cd "$ORIGINAL_DIR"

fi

java -version || ./install-java

grep -x 'export ANDROID_NDK_HOME=/opt/android-ndk' ~/.bashrc || echo -e '\nexport ANDROID_NDK_HOME=/opt/android-ndk' >> ~/.bashrc
