#!/bin/bash

set -e

which aptitude || sudo apt-get install -y aptitude
which git || sudo aptitude install -y git
which curl || sudo aptitude install -y curl

curl https://raw.github.com/creationix/nvm/master/install.sh | PROFILE=~/.bashrc sh

. ~/.nvm/nvm.sh
nvm install 0.10
nvm alias default 0.10
nvm use default
