#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

# Exit early if already installed
[ -f /etc/bash_completion.d/hub.bash_completion.sh ] && exit 0

ensureInstalled git bash-completion

cd "$(mktemp -d)"
githubDownload github/hub | tar xzv

cd hub*
$SUDO mv etc/hub.bash_completion.sh /etc/bash_completion.d/

$SUDO chown -R "$(id -un)" /usr/local
mkdir -p /usr/local/man/man1
mv share/man/man1/hub.1 /usr/local/man/
mv bin/hub /usr/local/bin/
