#!/bin/bash

set -e

which aptitude || sudo apt-get install -y aptitude
which tilda || sudo aptitude install -y tilda
which byobu || sudo aptitude install -y byobu
which tmuxinator || sudo aptitude install -y tmuxinator
which xsel || sudo aptitude install -y xsel

mkdir -p ~/.config/autostart
cat > ~/.config/autostart/tilda.desktop <<EOF
[Desktop Entry]
Type=Application
Exec=tilda
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=tilda
Name=tilda
Comment[en_US]=
Comment=
EOF

mkdir -p ~/.config/tilda
if [ ! -f ~/.config/tilda/config_0 ]; then
    if which xfconf-query; then
        wget -O ~/.config/tilda/config_0 https://raw.github.com/hugojosefson/tilda-configuration/xubuntu/config_0
    else
        wget -O ~/.config/tilda/config_0 https://raw.github.com/hugojosefson/tilda-configuration/master/config_0
    fi
fi

mkdir -p ~/code
mkdir -p ~/.tmuxinator
cat > ~/.tmuxinator/base.yml <<EOF
name: base

tmux_command: byobu-tmux

windows:
  - "": clear; sudo --list --non-interactive aptitude && (echo -n Press ENTER for dist-upgrade...; read -s;); sudo aptitude update && sudo aptitude dist-upgrade --purge-unused -y && sudo aptitude autoclean
  - top: top
  - code: cd ~/code && ll -ltra
EOF

cat > ~/.tmuxinator/temp.TEMPLATE <<\EOF
name: ${SESSION_NAME}
root: ${SESSION_DIR}

tmux_command: byobu-tmux

windows:
  - "":
EOF

cat > ~/.tmuxinator/mux.yml <<\EOF
name: mux
root: ~/.tmuxinator

tmux_command: byobu-tmux

windows:
  - mux: ls -lF
  - bin: cd ~/bin && ls -lFtr
  - dotfiles: cd ~/.dotfiles && ls -lF
  - mover: byobu select-window -t :0; exit
EOF

DOMAIN=${DOMAIN:-$(wbinfo --own-domain 2>/dev/null || true)}
cat > ~/bin/m-temp <<EOF
#!/bin/bash

## Creates and opens a new temp session

export SESSION_DIR=\$(readlink -f \${1:-\$(mktemp -d)})
export SESSION_NAME="\$(echo \${SESSION_DIR} \
                     | sed -r 's/^[\\./]//g' \
                     | sed -r 's/[\\./]+/-/g' \
                     | sed -r 's/^surviving-data-//' \
                     | sed -r 's/^home-${DOMAIN}-[^-]+-//' \
                     | sed -r 's/^home-${USER}-//' \
                     | sed -r 's/^code-//g')"
FILE_NAME="\${SESSION_NAME}.yml"

cd ~/.tmuxinator
envsubst < temp.TEMPLATE > "\${FILE_NAME}"

mkdir -p \${SESSION_DIR}
tmuxinator start \${SESSION_NAME}
sleep 1
rm "\${FILE_NAME}"
EOF
chmod +x ~/bin/m-temp

[[ -e ~/.bash_aliases ]] && mv ~/.bash_aliases{,.$(date +%s).backup}
cp ./.bash_aliases ~/
