#!/bin/bash
set -e

cd $(dirname $(mktemp))
wget https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb -O google-chrome-unstable_current_amd64.deb
sudo dpkg -i google-chrome-unstable_current_amd64.deb
