#!/bin/bash

set -e

which aptitude || sudo apt-get install -y aptitude
which curl || sudo aptitude install -y curl
which unzip || sudo aptitude install -y unzip

cd $(mktemp -d)

curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
mkdir -p ~/bin
./awscli-bundle/install -b ~/bin/aws

curl -o ~/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
chmod +x ~/bin/ecs-cli
