#!/bin/bash

set -e
cd $(dirname ${0})

if ! which CrashPlanDesktop; then
    if ! which hxnormalize; then
        which aptitude || sudo apt-get install -y aptitude
        sudo aptitude install -y html-xml-utils
    fi

    which java || ./install-java

    CURRENT_VERSION=$(hxnormalize https://support.code42.com/Release_Notes/CrashPlan_For_Home 2>/dev/null |grep 'id="Current_Version"' -A 7|awk -F '>' '/>[0-9].*<\/a>/{print $2}'|awk -F '<' '{print $1}')

    FILE=CrashPlan_${CURRENT_VERSION}_Linux.tgz
    DOWNLOAD_URL=http://download.code42.com/installs/linux/install/CrashPlan/${FILE}

    TEMP_DIR=$(dirname $(mktemp))
    TEMP_FILE=${TEMP_DIR}/${FILE}

    cd $TEMP_DIR
    wget --continue $DOWNLOAD_URL
    tar xzf $FILE
    cd crashplan-install

    # non-interactive install
    sed -r 's/^more /cat /g' -i install.sh
    sed -r 's/agreed=0/agreed=1/g' -i install.sh
    yes '' | sudo ./install.sh
fi

echo "*********************************************************************************"
echo "If the CrashPlanDesktop gui won't start, put this:"
echo " -Dorg.eclipse.swt.browser.DefaultType=mozilla"
echo " at the end of the GUI_JAVA_OPTS declaration in /usr/local/crashplan/bin/run.conf"
echo "*********************************************************************************"
