#!/bin/bash

set -e

which aptitude || sudo apt-get install -y aptitude

wget -qO - https://linux-packages.resilio.com/resilio-sync/key.asc | sudo apt-key add -
echo deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free | sudo tee /etc/apt/sources.list.d/resilio-sync.list
sudo aptitude update
sudo aptitude install -y resilio-sync

# Enable for current user
sudo sed -r 's/^WantedBy=multi-user.target$/WantedBy=default.target/g' -i /usr/lib/systemd/user/resilio-sync.service
systemctl --user enable resilio-sync
systemctl --user start resilio-sync

echo Resilio Sync is now available for $USER on http://localhost:8888/gui