#!/bin/bash

set -e

if ! which plexhometheater.sh; then
    sudo apt-add-repository -y ppa:plexapp/plexht
    sudo apt-add-repository -y ppa:pulse-eight/libcec
    which aptitude || sudo apt-get install -y aptitude
    sudo aptitude update
    sudo aptitude install -y plexhometheater
fi
