#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

function addAptSource() {
  local codename="${1}"
  echo "deb http://apt.insync.io/ubuntu ${codename} non-free contrib" | $SUDO tee /etc/apt/sources.list.d/insync.list
  $SUDO apt-get update
}

$SUDO apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ACCAF35C || \
$SUDO apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys ACCAF35C

addAptSource "$(ubuntuCodename)" || addAptSource bionic
ensureInstalled insync insync-nautilus
