#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

mkdir -p ~/bin

cat > ~/bin/gk <<EOF
#!/usr/bin/env bash
arg=\${1:---all}
gitk "\${arg}" &>/dev/null &
EOF

chmod +x ~/bin/gk
