#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

isInstalled xpra && exit 0

curl -s "https://xpra.org/gpg.asc" | $SUDO apt-key add -
curl -s "https://xpra.org/repos/$(ubuntuCodename)/xpra.list" | $SUDO tee /etc/apt/sources.list.d/xpra.list

$SUDO apt update
ensureInstalled xpra
