#!/bin/bash

set -e

# Exit early if already installed
if (grep 'alias git=hub' ~/.bash_aliases); then
  which hub && exit 0
fi

which aptitude || sudo apt-get install -y aptitude
which git || sudo aptitude install -y git
sudo aptitude install -y bash-completion

cd $(mktemp -d)

DOWNLOAD_URL=$(wget -O - --quiet https://api.github.com/repos/github/hub/releases/latest|grep browser_download_url|grep linux-amd64|cut -d '"' -f 4)
curl --location --tlsv1.2 ${DOWNLOAD_URL} | tar xzv

cd hub*

sudo mv etc/hub.bash_completion.sh /etc/bash_completion.d/

sudo chown -R $USER:$GROUP /usr/local
mkdir -p /usr/local/man/man1
mv man/hub.1 /usr/local/man/
mv hub /usr/local/bin/

grep 'alias git=hub' ~/.bash_aliases || echo 'alias git=hub' >> ~/.bash_aliases
