#!/bin/bash

set -e

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
which aptitude || sudo apt-get install -y aptitude
sudo aptitude install -y apt-transport-https
sudo aptitude update
sudo aptitude install -y lxc-docker cgroup-lite
sudo gpasswd -a ${USER} docker
sudo service docker restart
sleep 2
sudo su - $USER -c 'docker run -i -t busybox echo "Hello from inside Docker!"'

curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-$(uname -s)-$(uname -m) > ~/bin/docker-compose
chmod +x ~/bin/docker-compose
sudo sh -c "curl -L https://raw.githubusercontent.com/docker/compose/1.2.0/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose"

cd $(mktemp -d)
git clone https://gist.github.com/76b450a0c986e576e98b.git
cd 76b450a0c986e576e98b
mv docker-cleanup ~/bin/
chmod +x ~/bin/docker-cleanup
