#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

command -v rua >/dev/null 2>&1 && exit 0

./install-rust
ensureInstalled git base-devel bubblewrap-suid xz shellcheck

RUSTUP_TOOLCHAIN=stable cargo install --force rua
