#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

ensureInstalledFlatpak "com.jetbrains.IntelliJ-IDEA-Community"

mkdir -p ~/bin

cat > ~/bin/i <<EOF
#!/usr/bin/env bash
arg=\${1:-.}
idea "\${arg}" &>/dev/null &
EOF

chmod +x ~/bin/i
