#!/bin/bash

set -e

sudo aptitude install -y tilda byobu
mkdir -p ~/.config/autostart
cat > ~/.config/autostart/tilda.desktop <<EOF
[Desktop Entry]
Type=Application
Exec=tilda
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=tilda
Name=tilda
Comment[en_US]=
Comment=
EOF
