#!/bin/bash

set -e

if ! which firefox-trunk; then
    sudo apt-add-repository -y ppa:ubuntu-mozilla-daily/ppa
    which aptitude || sudo apt-get install -y aptitude
    sudo aptitude update
    sudo aptitude install -y firefox-trunk
fi
