#!/bin/bash

set -e

which aptitude || sudo apt-get install -y aptitude

if ! which spotify; then
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94558F59
    echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
    sudo aptitude update
    sudo aptitude install -y spotify-client
fi
