#!/bin/bash

set -e

. /etc/lsb-release

sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo sh -c "echo deb https://apt.dockerproject.org/repo ubuntu-$DISTRIB_CODENAME main > /etc/apt/sources.list.d/docker.list"
which aptitude || sudo apt-get install -y aptitude
sudo aptitude install -y apt-transport-https ca-certificates
sudo aptitude update
sudo aptitude install -y docker-engine cgroup-lite
sudo gpasswd -a ${USER} docker
sudo service docker restart
sleep 2
sudo su - $USER -c "docker run hello-world"

mkdir -p ~/bin

curl -L  https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > ~/bin/docker-compose
chmod +x ~/bin/docker-compose
sudo sh -c "curl -L https://raw.githubusercontent.com/docker/compose/1.6.0/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose"

cd $(mktemp -d)
git clone https://gist.github.com/76b450a0c986e576e98b.git
cd 76b450a0c986e576e98b
mv docker-cleanup ~/bin/
chmod +x ~/bin/docker-cleanup
