#!/bin/bash

set -e

echo ===============================================================
echo When this script causes your computer to go blank or whatever,
echo please reboot, login, and re-run the script.
echo It will then continue where it left off.
echo ===============================================================
echo -n "Press ENTER to continue."
read

sudo apt-add-repository -y ppa:gnome3-team/gnome3-next
sudo apt-add-repository -y ppa:gnome3-team/gnome3-staging
which aptitude || sudo apt-get install -y aptitude
sudo aptitude update
sudo aptitude dist-upgrade --purge -y
sudo aptitude install -y ubuntu-gnome-desktop

gsettings set org.gnome.desktop.interface text-scaling-factor 1.0

echo $(which gdm) | sudo tee /etc/X11/default-display-manager

firefox https://extensions.gnome.org/extension/615/appindicator-support/ &

echo ===============================================================
echo Enable the gnome extension I so helpfully opened for you in
echo Firefox, if you want to be able to see Skype, Dropbox and
echo similar apps in the system tray.
echo ===============================================================
