#!/bin/bash

set -e

ORIGINAL_DIR="$(pwd)"

which aptitude || sudo apt-get install -y aptitude
which curl || sudo apt-get install -y curl
which jq || sudo apt-get install -y jq
which wget || sudo apt-get install -y wget

DOWNLOAD_URL=$(curl --silent 'https://data.services.jetbrains.com/products/releases?code=IIU,IIC&latest=true&type=release' | jq -r .IIC[0].downloads.linux.link)
FILENAME=$(echo $DOWNLOAD_URL | rev | cut -d '/' -f 1 | rev)
FILE=$(dirname $(mktemp))/$FILENAME

wget --continue ${DOWNLOAD_URL} -O $FILE
DIR=$(tar tzf $FILE |head -n 1|cut -d '/' -f 1)

sudo chown $USER:$GROUP /opt
tar xzf $FILE -C /opt
cd /opt
rm idea || true
ln -s $DIR idea

cd "$ORIGINAL_DIR"
java -version || ./install-java

which idea || /opt/idea/bin/idea.sh
sed -r "s/${DIR}/idea/g" -i /usr/local/bin/idea || true
