#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

# Exit early if already installed
[ -f /usr/local/bin/yq ] && exit 0

$SUDO chown -R "$(id -un)" /usr/local
githubDownload mikefarah/yq > /usr/local/bin/yq
chmod +x /usr/local/bin/yq
