#!/bin/bash

set -e

which aptitude || sudo apt-get install -y aptitude
which curl || sudo aptitude install -y curl

cd $(mktemp -d)

curl -O https://prerelease.keybase.io/keybase_amd64.deb
sudo dpkg -i keybase_amd64.deb || sudo apt-get install -fy
run_keybase
