#!/bin/bash

set -e

which aptitude || sudo apt-get install -y aptitude
which gitk || sudo aptitude install -y gitk

mkdir -p ~/bin
echo > ~/bin/gk <<\EOF
#!/bin/bash
arg=${1:---all}
gitk "${arg}" &>/dev/null &
EOF
chmod +x ~/bin/gk
