#!/bin/bash

set -e

sudo aptitude install -y curl git

INSTALL_FILE=$(mktemp --suffix=nvm-install.sh)
curl https://raw.github.com/creationix/nvm/master/install.sh > ${INSTALL_FILE}
sh ${INSTALL_FILE} ~/.bashrc

. ~/.nvm/nvm.sh
nvm install 0.10
nvm alias default 0.10
nvm use default
