#!/bin/bash

set -e
cd $(dirname ${0})

ORIGINAL_DIR="$(pwd)"

which aptitude || sudo apt-get install -y aptitude
which curl || sudo apt-get install -y curl
which wget || sudo apt-get install -y wget

DOWNLOAD_URL=$(curl --silent http://www.jetbrains.com/webstorm/download/download_thanks.jsp|grep direct|cut -d '"' -f 6|sed -r 's/\.exe$/.tar.gz/')
FILENAME=$(echo $DOWNLOAD_URL | rev | cut -d '/' -f 1 | rev)
FILE=$(dirname $(mktemp))/$FILENAME

wget --continue ${DOWNLOAD_URL} -O $FILE
DIR=$(tar tzf $FILE |head -n 1|cut -d '/' -f 1)

sudo chown $USER:$GROUP /opt
tar xzf $FILE -C /opt
cd /opt
rm webstorm || true
ln -s $DIR webstorm

cd "$ORIGINAL_DIR"
java -version || ./install-java

which wstorm || /opt/webstorm/bin/webstorm.sh
sed -r "s/${DIR}/webstorm/g" -i /usr/local/bin/wstorm || true
