#!/bin/bash

set -e

which aptitude || sudo apt-get install -y aptitude
which tilda || sudo aptitude install -y tilda
which byobu || sudo aptitude install -y byobu

mkdir -p ~/.config/autostart

cat > ~/.config/autostart/tilda.desktop <<EOF
[Desktop Entry]
Type=Application
Exec=tilda
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=tilda
Name=tilda
Comment[en_US]=
Comment=
EOF

mkdir -p ~/.config/tilda

if [ ! -f ~/.config/tilda/config_0 ]; then
    wget -O ~/.config/tilda/config_0 https://raw.github.com/hugojosefson/tilda-configuration/master/config_0
fi
