#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

ensureInstalled curl base-devel
curl https://sh.rustup.rs -sSf | sh -s -- -y

ensureInFile ~/.bashrc '. "${HOME}/.cargo/env"'
. "${HOME}/.cargo/env"

cargo install \
  bat \
  exa \
  fd-find \
  ripgrep \
