#!/bin/bash

set -e

which aptitude || sudo apt-get install -y aptitude
which git || sudo aptitude install -y git
which rake || sudo aptitude install -y rake
cd $(mktemp -d)
git clone https://github.com/github/hub.git
cd hub
sudo chown -R $USER:$GROUP /usr/local
rake install prefix=/usr/local
grep 'alias git=hub' ~/.bash_aliases || echo 'alias git=hub' >> ~/.bash_aliases
