#!/bin/bash

set -e

mkdir -p ~/code
if [ ! -d ~/code/ubuntu-personal-configuration ]; then
    cd ~/code
    git clone https://hugojosefson@bitbucket.org/hugojosefson/ubuntu-personal-configuration.git
    cd ubuntu-personal-configuration
    ./all-configuration
else
    cd ~/code/ubuntu-personal-configuration
    git fetch
    git status
    ls -l
    echo Go ahead and run the personal configuration yourself.
fi
