#!/bin/bash

set -e

dpkg -l aptitude 2>&1 | grep ^ii >/dev/null || sudo apt-get install -y aptitude
dpkg -l corkscrew 2>&1 | grep ^ii >/dev/null || sudo aptitude install -y corkscrew

PROXY=${PROXY:-localhost:3128}
PROXY_HOST=${PROXY_HOST:-${PROXY%%:*}}
PROXY_PORT=${PROXY_PORT:-${PROXY#*:}}

sudo sed -r "s/^(\s*ProxyCommand.*)/#\1/g" -i /etc/ssh/ssh_config
sudo sed -r "s/^(Host \\*)\$/\1\\n    ProxyCommand corkscrew $PROXY_HOST $PROXY_PORT %h %p/g" -i /etc/ssh/ssh_config

echo Installed and configured corkscrew to access git ssh urls through the proxy $PROXY_HOST:$PROXY_PORT
