#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ./common.bash

./all-2-developer-base

./install-network-utils
./install-brave-browser
[[ ! insideDocker ]] && ensureInstalled chromium-browser
./install-chrome

