#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ./common.bash

./all-1-minimal-sanity

ensureInstalled git gitk meld

./install-github-cli
./install-github-git-plugin
./install-docker
./install-isolate-in-docker
./install-virtualization
