#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ./common.bash

./install-keybase
./install-yubikey
./install-nordvpn
./install-insync

./install-snap
sudo snap install signal-desktop
sudo snap install spotify
sudo snap install slack --classic

sudo apt purge --autoremove qlipper
