#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ./common.bash

ensureInstalled yubioath-desktop

./install-keybase
./install-yubikey
./install-nordvpn
./install-insync
./install-rust

if insideDocker; then
  echo "Not installing snaps, because snap is not available by default inside Docker." >&2
  exit 0
fi
./install-snap
echo Not running: sudo snap install signal-desktop
echo Not running: sudo snap install spotify
echo Not running: sudo snap install slack --classic
