#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")"
. ./common.bash

./update-packages

ensureInstalled \
  aptitude \
  flip \
  ncdu \
  network-manager-openvpn-gnome \
  jq \
  solaar \

./install-tmuxinator-byobu-bash_aliases
./install-vim
