#!/bin/bash

set -e

# Install security updates automatically.
sudo sed -r 's/APT::Periodic::Download-Upgradeable-Packages "0"/APT::Periodic::Download-Upgradeable-Packages "1"/' -i /etc/apt/apt.conf.d/10periodic
sudo sed -r 's/APT::Periodic::Unattended-Upgrade "0"/APT::Periodic::Unattended-Upgrade "1"/' -i /etc/apt/apt.conf.d/10periodic
