#!/bin/bash

set -e

ORIGINAL_DIR="$(pwd)"

if [ ! -f /opt/android-sdk-linux/tools/android ]; then
  which curl || sudo apt install -y curl
  which wget || sudo apt install -y wget
  which hxpipe || sudo apt install -y html-xml-utils
  
  DOWNLOAD_URL=$(curl --silent --location https://developer.android.com/studio/index.html | hxpipe | grep ^Ahref | grep sdk | grep linux | cut -d ' ' -f 3)
  FILENAME=$(echo $DOWNLOAD_URL | rev | cut -d '/' -f 1 | rev)
  FILE=$(dirname $(mktemp))/$FILENAME
  
  wget --continue ${DOWNLOAD_URL} -O $FILE
  DIR=$(tar tzf $FILE |head -n 1|cut -d '/' -f 1)
  
  sudo chown $USER:$GROUP /opt
  tar xzf $FILE -C /opt
fi

java -version || install-java
 
echo "If it hangs on downloading URLs, edit install-android-sdk and uncomment PROXY_ARGUMENTS" 
PROXY_ARGUMENTS=""
#PROXY_ARGUMENTS="--proxy-host localhost --proxy-port 3128"
( sleep 2; while [ 1 ]; do sleep 1; echo y; done ) | /opt/android-sdk-linux/tools/android update sdk --no-ui ${PROXY_ARGUMENTS} --filter tool,platform-tool # --all --force

grep -x 'export PATH=/opt/android-sdk-linux/platform-tools:/opt/android-sdk-linux/tools:$PATH' ~/.bashrc || echo -e '\nexport PATH=/opt/android-sdk-linux/platform-tools:/opt/android-sdk-linux/tools:$PATH' >> ~/.bashrc
grep -x 'export ANDROID_HOME=/opt/android-sdk-linux' ~/.bashrc || echo -e '\nexport ANDROID_HOME=/opt/android-sdk-linux' >> ~/.bashrc
