#!/usr/bin/env bash

set -e

which nmap || sudo apt install -y nmap
which mtr || sudo apt install -y mtr-tiny
which wireshark || sudo DEBIAN_FRONTEND=noninteractive apt install -y wireshark
which corkscrew || sudo apt install -y corkscrew
sudo apt install -y netcat-traditional
