#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ./common.bash

if insideDocker; then
  echo "Not installing aws-cli, because snap is not available by default inside Docker." >&2
  exit 0
fi

./install-snap
sudo snap install intellij-idea-community --classic
sudo snap alias intellij-idea-community idea
