#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")"
. ./common.bash

# Exit early if already installed
[ -f /etc/bash_completion.d/hub.bash_completion.sh ] && exit 0

ensureInstalled git bash-completion

cd "$(mktemp -d)"
githubDownload github/hub | tar xzv

cd hub*
sudo mv etc/hub.bash_completion.sh /etc/bash_completion.d/
