#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ./common.bash

function addAptSource() {
  local codename="${1}"
  echo deb http://apt.insynchq.com/ubuntu ${codename} non-free contrib | sudo tee /etc/apt/sources.list.d/insync.list
  sudo apt-get update
}

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ACCAF35C || \
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys ACCAF35C

addAptSource $(ubuntuCodename) || addAptSource bionic
ensureInstalled insync insync-nautilus
