#!/usr/bin/env bash

set -e

#which google-chrome-stable && exit 0

sudo dnf install -y fedora-workstation-repositories
sudo dnf config-manager --set-enabled google-chrome
sudo dnf install -y google-chrome-stable
