#!/usr/bin/env bash

set -e

which docker && exit 0

curl -fSL https://get.docker.com/ | sudo su - -c sh

## https://jrruethe.github.io/blog/2016/04/15/running-docker-in-qubes/
sudo systemctl disable docker

# Allow current user access to docker
sudo groupadd -f docker
sudo usermod -aG docker $USER

sudo apt install -y bash-completion
sudo su - -c "curl -L https://raw.githubusercontent.com/docker/compose/1.22.0/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose"
