#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ./common.bash

ensureInstalled fedora-workstation-repositories 'dnf-command(config-manager)'

sudo dnf config-manager --set-enabled google-chrome
ensureInstalled google-chrome-unstable
