#!/bin/bash

set -e

which apt-add-repository || sudo apt install -y software-properties-common

if ! which yubikey-personalization-gui; then
    sudo apt-add-repository -y ppa:yubico/stable
    sudo apt update
    sudo apt install -y yubikey-personalization-gui
fi
