#!/usr/bin/env bash

set -e

which snap || sudo dnf install -y snapd
[ -L /snap ] || sudo ln -s /var/lib/snapd/snap /
sudo service snapd start
grep -x 'PATH=/snap/bin:$PATH' /etc/environment || (echo -e '\nPATH=/snap/bin:$PATH' | sudo tee -a /etc/environment)
