#!/usr/bin/env bash

set -e

ORIGINAL_DIR="$(pwd)"

if [ ! -d /opt/apache-maven/ ]; then
  which curl || sudo dnf install -y curl
  which wget || sudo dnf install -y wget
  which hxpipe || sudo dnf install -y html-xml-utils

  DOWNLOAD_URL=$(curl --silent http://maven.apache.org/download.cgi | hxpipe | grep ^Ahref | grep binaries/apache-maven | grep tar.gz\$ | head -n 1 | cut -d ' ' -f 3)
  FILENAME=$(echo $DOWNLOAD_URL | rev | cut -d '/' -f 1 | rev)
  FILE=$(dirname $(mktemp))/$FILENAME
  
  wget --continue ${DOWNLOAD_URL} -O $FILE
  DIR=$(tar tf $FILE |head -n 1|cut -d '/' -f 1)
  
  sudo chown $USER:$GROUP /opt
  tar xf $FILE -C /opt
  cd /opt
  rm apache-maven || true
  ln -s $DIR apache-maven
  cd "$ORIGINAL_DIR"

fi

java -version || install-java
grep -x 'PATH=/opt/apache-maven/bin:$PATH' /etc/environment || echo -e '\nPATH=/opt/apache-maven/bin:$PATH' | sudo tee -a /etc/environment
grep -x 'M2_HOME=/opt/apache-maven' /etc/environment || echo -e '\nM2_HOME=/opt/apache-maven' | sudo tee -a /etc/environment
