#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ./common.bash

ensureInstalled snapd
[ -L /snap ] || [ -d /snap ] || ( [ -d /var/lib/snapd/snap ] && sudo ln -s /var/lib/snapd/snap / )
sudo service snapd restart
grep -x 'export PATH=/snap/bin:$PATH' ~/.bashrc || echo -e '\nexport PATH=/snap/bin:$PATH' >> ~/.bashrc
