#!/bin/bash

set -e
cd $(dirname ${0})

ORIGINAL_DIR="$(pwd)"

which curl || sudo apt-get install -y curl
which wget || sudo apt-get install -y wget
which jq || sudo apt-get install -y jq

DOWNLOAD_URL=${1:-$(curl --silent 'https://data.services.jetbrains.com/products/releases?code=WS&latest=true&type=release' | jq -r .WS[0].downloads.linux.link)}
FILENAME=$(echo $DOWNLOAD_URL | rev | cut -d '/' -f 1 | rev)
FILE=$(dirname $(mktemp))/$FILENAME

wget --continue ${DOWNLOAD_URL} -O $FILE
DIR=$(tar tzf $FILE |head -n 1|cut -d '/' -f 1)

sudo chown $USER:$GROUP /opt
tar xzf $FILE -C /opt
cd /opt
rm webstorm || true
ln -s $DIR webstorm

cd "$ORIGINAL_DIR"
java -version || install-java

if [ -n "$DISPLAY" ]; then
    which webstorm || /opt/webstorm/bin/webstorm.sh
    sudo sed -r "s/${DIR}/webstorm/g" -i /usr/local/bin/webstorm /usr/share/applications/jetbrains-webstorm.desktop || true
else
    echo Skipping setting up webstorm executable, because there is no DISPLAY set.
fi

mkdir -p ~/bin
echo > ~/bin/ws <<\EOF
#!/bin/bash
arg=${1:-.}
webstorm "${arg}" &>/dev/null &
EOF
chmod +x ~/bin/ws
