#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ./common.bash

DOWNLOAD_URL=$(curl -s https://api.github.com/repos/cli/cli/releases/latest|grep browser_download_url|grep linux_amd64.rpm|cut -d '"' -f 4)
ensureInstalled "${DOWNLOAD_URL}"
