#!/usr/bin/env bash

set -e

which google-chrome-unstable && exit 0

cd $(dirname $(mktemp))
wget https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb -O google-chrome-unstable_current_amd64.deb
sudo dpkg -i google-chrome-unstable_current_amd64.deb
