#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ./common.bash

ensureInstalled curl gdebi-core

cd "$(mktemp -d)"

curl -s --remote-name https://prerelease.keybase.io/keybase_amd64.deb
sudo gdebi --non-interactive keybase_amd64.deb
