#!/bin/bash

set -e
cd $(dirname ${0})
. ./common.bash

if ! isInstalled yubikey-personalization-gui; then
    ensureInstalled software-properties-common
    sudo apt-add-repository -y ppa:yubico/stable
    sudo apt update
    ensureInstalled yubikey-personalization-gui
fi
