#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")"
. ./common.bash

ensureInstalled software-properties-common
sudo add-apt-repository -y ppa:stefanberger/swtpm-focal

ensureInstalled virt-manager ovmf swtpm swtpm-tools
