#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")"
. ./common.bash

ensureInstalled \
  byobu \
  tmux \
  tmuxinator \
  alacritty \
  xsel \

isInstalled screen && sudo apt-get purge -y --auto-remove screen

./install-tabbed
