#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ./common.bash

ensureInstalled curl

cd $(mktemp -d)

curl -O https://prerelease.keybase.io/keybase_amd64.deb
sudo dpkg -i keybase_amd64.deb || sudo apt install -fy