#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ./common.bash

isInstalled xpra && exit 0

curl -s https://xpra.org/gpg.asc | sudo apt-key add -
curl -s https://xpra.org/repos/$(ubuntuCodename)/xpra.list | sudo tee /etc/apt/sources.list.d/xpra.list

sudo apt update
ensureInstalled xpra
