#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")"
. ./common.bash

ensureInstalled \
  build-essential \
  git \
  libxft-dev \
  alacritty \
  coreutils \
  procps \
  xdotool \

cd "$(mktemp -d)"
git clone https://github.com/hugojosefson/tabbed
cd tabbed
make
sudo make install

mkdir -p ~/bin
cp extra-tools/* ~/bin/
