#!/usr/bin/env bash

set -e

which gdebi || sudo apt install -y gdebi-core

cd $(dirname $(mktemp))
wget https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb -O google-chrome-unstable_current_amd64.deb
sudo gdebi --non-interactive google-chrome-unstable_current_amd64.deb
