#!/bin/bash

set -e

# Exit early if no packages seem to need upgrading
apt-get -s -o Debug::NoLocking=true upgrade | grep -q ^Inst || exit 0

sudo apt update
sudo apt dist-upgrade --purge-unused -y
sudo apt autoclean
