#!/bin/bash

# Based on http://blog.tkassembled.com/364/intel-graphics-on-a-2011-macbook-pro-in-linux/
# TODO: Finish this script with the actual grub config

set -e
LONG_VERSION=$(uname -r)
SHORT_VERSION=$(echo ${LONG_VERSION}|cut -d '-' -f 1)
CPUS=$(cat /proc/cpuinfo |grep ^processor\\s|wc -l)
THREADS=$[2*${CPUS}]
sudo aptitude install -y build-essential kernel-package libncurses5-dev git linux-source linux-headers-${LONG_VERSION}
cd /usr/src/linux-source-${SHORT_VERSION}
sudo tar xvf linux-source-${SHORT_VERSION}.tar.bz2
cd linux-source-${SHORT_VERSION}
sudo cp ../../linux-headers-${LONG_VERSION}/.config .
sudo sed -r 's/CONFIG_DRM_I915=m/CONFIG_DRM_I915=y/' -i .config
sudo make-kpkg --initrd --jobs ${THREADS} --append_to_version +igd kernel_image
sudo make-kpkg --initrd --jobs ${THREADS} --append_to_version +igd kernel_headers
sudo dpkg -i ../linux-headers-${SHORT_VERSION}+igd_${SHORT_VERSION}+igd-10.00.Custom_amd64.deb
sudo dpkg -i ../linux-image-${SHORT_VERSION}+igd_${SHORT_VERSION}+igd-10.00.Custom_amd64.deb
