#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

./all-1-minimal-sanity

./install-git

ensureInstalled \
  git-revise \
  gitk \
  meld \
  moreutils \
  tig \

./install-github-cli
./install-github-git-plugin
./install-docker
./install-isolate-in-docker
./install-virt-manager
