#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

./all-2-developer-base

./install-network-utils
./install-brave-browser
ensureInstalled chromium-browser
ensureInstalled google-chrome-stable
