#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

ensureInstalled \
  base-devel \
  git \
  libxft-dev \
  alacritty \
  coreutils \
  procps \
  xdotool \

cd "$(mktemp -d)"
git clone https://github.com/hugojosefson/tabbed
cd tabbed
make
$SUDO make install

mkdir -p ~/bin
cp extra-tools/* ~/bin/
