#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

ensureInstalled git
git clone "https://github.com/magicmonty/bash-git-prompt.git" ~/.bash-git-prompt || (cd ~/.bash-git-prompt && git pull)
grep -x '. ~/.bash-git-prompt/gitprompt.sh' ~/.bashrc || echo -e '\n. ~/.bash-git-prompt/gitprompt.sh' >> ~/.bashrc
