#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash



[[ -e ~/.bash_aliases ]] && mv ~/.bash_aliases{,".$(date +%s).backup"}
cp ./.bash_aliases ~/
grep -x '. ~/.bash_aliases' ~/.bashrc || echo -e '\n. ~/.bash_aliases' >> ~/.bashrc
