#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")"
. ../sys/common.bash

./all-1-minimal-sanity

./install-gitk
./install-git-prompt
./install-github-git-plugin

./install-idea
./install-webstorm
./add-node_modules-bin-to-path
./install-fzf
