#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
cd "$(dirname "${0}")"
. ./common.bash

./all-1-minimal-sanity

./install-gitk
./install-git-prompt
./install-github-git-plugin
./install-fzf
./install-mdr
