#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")"
. ../sys/common.bash

./disable-some-keyboard-shortcuts
./install-keybase
./install-rust

flatpak install --or-update --user --noninteractive \
  org.signal.Signal \
  com.spotify.Client \
  com.slack.Slack \
  com.microsoft.Teams \
