#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ../sys/common.bash

ensureInstalled git curl

curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | PROFILE=~/.bashrc bash

. ~/.nvm/nvm.sh

nvm install 10
nvm exec 10 npm install -g npm@latest
nvm exec 10 npm install -g yarn@latest

nvm install stable
nvm exec stable npm install -g npm@latest
nvm exec stable npm install -g yarn@latest

nvm alias default stable
nvm use default
