#!/usr/bin/env bash

set -e

which git || sudo apt install -y git
which curl || sudo apt install -y curl

curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | PROFILE=~/.bashrc bash

. ~/.nvm/nvm.sh

nvm install 8
nvm exec 8 npm install -g npm@latest
nvm exec 8 npm install -g yarn@latest

nvm install stable
nvm exec stable npm install -g npm@latest
nvm exec stable npm install -g yarn@latest

nvm alias default stable
nvm use default