#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")"
. ../sys/common.bash

ensureInstalled git

if [[ -d ~/.fzf ]]; then
  cd ~/.fzf
  git pull --rebase --autostash
else
  git clone --depth 1 "https://github.com/junegunn/fzf.git" ~/.fzf
fi

~/.fzf/install --all
