#!/usr/bin/env bash

set -e

if [ -n "$DISPLAY" ]; then
    which idea || snap run idea
else
    echo Skipping setting up idea executable, because there is no DISPLAY set.
fi

mkdir -p ~/bin
cat > ~/bin/i <<EOF
#!/usr/bin/env bash
arg=\${1:-.}
idea "\${arg}" &>/dev/null &
EOF
chmod +x ~/bin/i
