#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")"
. ../sys/common.bash

mkdir -p ~/code
mkdir -p ~/.tmuxinator
cat > ~/.tmuxinator/base.yml <<EOF
name: base

tmux_command: byobu-tmux

windows:
  - code: cd ~/code && ll -la
  - top: top
  - "": clear; sudo --list --non-interactive apt && (echo -n Press ENTER for full-upgrade...; read -s;); sudo apt update && sudo apt full-upgrade --auto-remove --purge -y && sudo apt autoclean
EOF

cat > ~/.tmuxinator/temp.TEMPLATE <<\EOF
name: ${SESSION_NAME}
root: ${SESSION_DIR}

tmux_command: byobu-tmux

windows:
  - "":
EOF

cat > ~/.tmuxinator/mux.yml <<\EOF
name: mux
root: ~/.tmuxinator

tmux_command: byobu-tmux

windows:
  - mux: ls -lF
  - bin: cd ~/bin && ls -lFtr
  - dotfiles: cd ~/dotfiles && ls -lF
  - mover: byobu select-window -t :0; exit
EOF

DOMAIN=${DOMAIN:-$(wbinfo --own-domain 2>/dev/null || true)}
mkdir -p ~/bin
cat > ~/bin/m-temp <<EOF
#!/usr/bin/env bash

## Creates and opens a new temp session

export SESSION_DIR="\$(readlink -f "\${1:-"\$(mktemp -d)"}")"
export SESSION_NAME="\$(echo "\${SESSION_DIR}" \
                     | sed -E 's/^[\\./]//g' \
                     | sed -E 's/[\\./]+/-/g' \
                     | sed -E 's/[åä]/a/g' \
                     | sed -E 's/[ÅÄ]/A/g' \
                     | sed -E 's/[ö]/o/g' \
                     | sed -E 's/[Ö]/O/g' \
                     | sed -E 's/^Users-/home-/' \
                     | sed -E 's/^home--[^-]+-//' \
                     | sed -E 's/^home-$(id -un)-//' \
                     | sed -E 's/^surviving-data-//' \
                     | sed -E 's/^code-//g')"
FILE_NAME="\${SESSION_NAME}.yml"

cd ~/.tmuxinator
envsubst < temp.TEMPLATE > "\${FILE_NAME}"

mkdir -p "\${SESSION_DIR}"
tmuxinator start "\${SESSION_NAME}"
sleep 1
rm "\${FILE_NAME}"
EOF
chmod +x ~/bin/m-temp

[[ -e ~/.bash_aliases ]] && mv ~/.bash_aliases{,".$(date +%s).backup"}
cp ./.bash_aliases ~/
grep -x '. ~/.bash_aliases' ~/.bashrc || echo -e '\n. ~/.bash_aliases' >> ~/.bashrc
