#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ../sys/common.bash

ensureInstalled git curl

curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | PROFILE=~/.bashrc bash

. ~/.nvm/nvm.sh

function installNodeVersion() {
  local nodeVersion=$1
  nvm install $nodeVersion
  nvm exec $nodeVersion npm install -g npm@latest
  nvm exec $nodeVersion npm install -g yarn@latest
}

installNodeVersion --lts
installNodeVersion stable

nvm alias default stable
nvm use default
