#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")"
. ../sys/common.bash

flatpak install --or-update --user --noninteractive com.jetbrains.IntelliJ-IDEA-Community

mkdir -p ~/bin

cat > ~/bin/i <<EOF
#!/usr/bin/env bash
arg=\${1:-.}
idea "\${arg}" &>/dev/null &
EOF

chmod +x ~/bin/i
