#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ../sys/common.bash

ensureInstalled git
git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt || (cd ~/.bash-git-prompt && git pull)
grep -x '. ~/.bash-git-prompt/gitprompt.sh' ~/.bashrc || echo -e '\n. ~/.bash-git-prompt/gitprompt.sh' >> ~/.bashrc
