#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")"
. ../sys/common.bash

# Not installing package locally. Using webstorm via isolate-in-docker.
# flatpak install --or-update --user --noninteractive com.jetbrains.WebStorm

mkdir -p ~/bin

cat > ~/bin/ws <<EOF
#!/usr/bin/env bash
arg=\${1:-.}
webstorm "\${arg}" &>/dev/null &
EOF

chmod +x ~/bin/ws
