#!/usr/bin/env bash

set -e

mkdir -p ~/bin

curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o ~/bin/docker-compose
chmod +x ~/bin/docker-compose

cd $(mktemp -d)
git clone https://gist.github.com/76b450a0c986e576e98b.git
cd 76b450a0c986e576e98b
mv docker-cleanup ~/bin/
chmod +x ~/bin/docker-cleanup
