#!/usr/bin/env bash

set -e

if [ -n "$DISPLAY" ]; then
    which webstorm || snap run webstorm
else
    echo Skipping setting up webstorm executable, because there is no DISPLAY set.
fi

mkdir -p ~/bin
cat > ~/bin/ws <<EOF
#!/usr/bin/env bash
arg=\${1:-.}
webstorm "\${arg}" &>/dev/null &
EOF
chmod +x ~/bin/ws
