#!/usr/bin/env bash

set -e
cd $(dirname ${0})
. ../sys/common.bash

cd $(mktemp -d)
git clone https://gist.github.com/76b450a0c986e576e98b.git
cd 76b450a0c986e576e98b
mv docker-cleanup ~/bin/
chmod +x ~/bin/docker-cleanup
