#!/usr/bin/env bash

set -e
cd "$(dirname "${0}")"
. ../sys/common.bash

# Exit early if already installed
[ -f /usr/local/bin/yq ] && exit 0

sudo chown -R "$(id -un)" /usr/local
githubDownload mikefarah/yq > /usr/local/bin/yq
chmod +x /usr/local/bin/yq
